In [1]:
import glob
import pandas as pd

In [2]:
ensg_with_weights=[x.split('.')[1] for x in glob.glob('WEIGHTS/ALL/*RDat')]

In [3]:
# load LUT
tab=pd.read_table('~/Data/ensg_enst_gene_mapping.txt')
lut=dict(zip(tab['Gene name'], tab['Gene stable ID']))

In [37]:
lut['TP53TG3C'] in ensg_with_weights

True

In [4]:
# load genes with weights computed from first computation
genes_with_weights = open('/cellar/users/jlz014/fusion_twas-master/WEIGHTS-with-filter/tcga-brca_genes_with_weights_names.txt').read().splitlines()

In [5]:
# convert genes with weights to ensg
ensg_init=[lut[g] if g in lut.keys() else 'NA' for g in genes_with_weights]

In [6]:
# zip
genes_ensg=dict(zip(ensg_init,genes_with_weights))

In [38]:
# genes from initial computation with weights computed in second computation
computed=list(set(ensg_init)&set(ensg_with_weights))

In [41]:
ensg=lut['TP53TG3C']
print(ensg)
gene_symbol=genes_ensg[ensg]
print(gene_symbol)

ENSG00000205457
TP53TG3C

In [11]:
# load expr matrix
ensg_expr_log2=pd.read_table('~/Data/TCGA/expression/TCGAmatrix.realign.gene.ENSG.BRCA-with-chr.log2.1-22.txt')

In [12]:
ensg_expr_log2.head()

,gene,chr,start,end,TCGA-GM-A2DO,TCGA-OL-A6VQ,TCGA-E9-A295,TCGA-A2-A0YL,TCGA-AQ-A54O,TCGA-BH-A0E7,...,TCGA-D8-A27N,TCGA-A8-A08C,TCGA-E2-A150,TCGA-LL-A8F5,TCGA-AQ-A1H3,TCGA-A2-A1FW,TCGA-BH-A0E1.2,TCGA-BH-A0E1.3,TCGA-B6-A0X5,TCGA-S3-AA17
0,ENSG00000000419,20,49552684,49575069,4.594585,5.330341,5.377702,5.294534,6.084816,5.568671,...,5.350385,4.911451,6.240199,4.937844,5.485918,5.730940,5.365442,5.228744,5.370727,5.473177
1,ENSG00000000457,1,169828259,169863093,2.266711,4.457881,3.407344,4.139861,2.648528,3.866892,...,4.081518,4.513771,3.376393,1.279113,5.035567,3.411687,4.237941,3.369316,3.403923,3.107914
2,ENSG00000000460,1,169764549,169823221,2.054184,3.018864,2.397177,3.554732,1.951312,2.418676,...,3.359843,2.888503,3.509661,1.924558,3.542917,2.724453,3.457735,1.416787,3.604322,2.478461
3,ENSG00000000938,1,27949917,27952751,3.989014,3.276037,1.757013,2.190045,1.772190,0.819386,...,2.811651,1.342458,2.443602,0.554715,2.599324,1.167078,0.992159,0.994044,-0.634781,3.426124
4,ENSG00000000971,1,196706037,196710216,3.140380,5.305784,5.587811,5.165815,0.881273,3.165066,...,4.873838,3.313243,3.632880,1.922469,5.226297,4.242926,3.834988,4.213269,3.052479,4.112245

In [13]:
all_genes=ensg_expr_log2['gene']

In [14]:
idx=list(all_genes).index(lut[gene_symbol])

In [15]:
ensg_expr_log2.iloc[idx,:]['gene']==ensg

True

In [16]:
print(idx)

4391

In [42]:
wgt_matrix=pd.read_table('~/fusion_twas-master/'+ensg+'.'+gene_symbol+'.wgt.matrix.txt')

In [43]:
wgt_matrix

                 blup      top1      enet
rs62044684   0.006741  1.034854  0.000000
rs450923    -0.003337  0.001947  0.000000
rs678286    -0.003882 -0.013446  0.000000
rs440384    -0.003927 -0.017143  0.000000
rs669012     0.005922  0.470316  0.000000
rs683980    -0.002341  0.049695  0.000000
rs690644     0.005884  0.396878  0.000000
rs605357    -0.004215 -0.325170  0.000000
rs690025     0.001005  0.184739  0.000000
rs4967890    0.000377  0.129383  0.000000
rs384388    -0.002292 -0.089955  0.000000
rs113573255 -0.006011 -0.239679  0.000000
rs62046793   0.006025  0.673322  0.000000
rs139628301 -0.004737 -0.357404  0.000000
rs62046844   0.003342  0.322110  0.000000
rs34464625   0.008343  1.053897  0.000000
rs4247845   -0.034820 -2.340621 -0.018636
rs11643832  -0.029382 -1.969391  0.000000
rs7187150   -0.002385 -0.432368  0.000000
rs4566180   -0.005208 -0.801614  0.000000
rs9934972   -0.026467 -1.635672  0.000000
rs11644945  -0.033571 -2.359570 -0.025008
rs357987     0.012841  0.704020  0.000000
rs6565360   -0.015239 -1.074660  0.000000
rs9935627   -0.028997 -1.662190  0.000000
rs7188064   -0.024573 -1.643261  0.000000
rs1842121   -0.023569 -1.608101  0.000000
rs11863843  -0.028793 -1.910906  0.000000
rs4887691   -0.031847 -2.277968 -0.006244
rs7500776   -0.023388 -1.818192  0.000000
...               ...       ...       ...
rs241923     0.006101  1.149374  0.000000
rs28678046   0.013296  1.688316  0.000000
rs3853343    0.014933  1.767410  0.000000
rs3853347    0.013296  1.688316  0.000000
rs28671716   0.013296  1.688316  0.000000
rs3853349    0.013296  1.688316  0.000000
rs3844516    0.008981  1.472339  0.000000
rs3853352    0.018448  1.973700  0.000000
rs4887619    0.008981  1.472339  0.000000
rs28514443   0.011677  1.608664  0.000000
rs28558890   0.011677  1.608664  0.000000
rs62039280   0.011866  1.613725  0.000000
rs35435529   0.005767  0.842468  0.000000
rs28626961   0.013426  1.707091  0.000000
rs1985776    0.009535  1.466951  0.000000
rs2335199    0.011718  0.743197  0.000000
rs2067108    0.013066  1.687070  0.000000
rs241915     0.003359  0.580836  0.000000
rs720126    -0.000242  0.063871  0.000000
rs71376354   0.019118  1.161695  0.000000
rs2019670    0.015021  1.533162  0.000000
rs2002923    0.015021  1.533162  0.000000
rs2075113    0.015021  1.533162  0.000000
rs492688     0.024434  1.576958  0.003126
rs1808306    0.015021  1.533162  0.000000
rs1966417    0.015021  1.533162  0.000000
rs241918    -0.001109  0.196576  0.000000
rs62037624   0.005110  0.738035  0.000000
rs242782     0.007954  0.686080  0.000000
rs242780     0.012633  1.049558  0.000000

[100 rows x 3 columns]

In [54]:
abs_weights=abs(wgt_matrix['enet'])
max_wgt_idx=list(abs_weights).index(max(abs_weights))

In [55]:
wgt_matrix.iloc[max_wgt_idx,:].name

'rs11644945'

In [56]:
set(wgt_matrix['enet'])

{-0.0250084821199383,
 -0.0186355009510286,
 -0.00624350578263603,
 0.0,
 0.0031264757603155103,
 0.00632010921733425,
 0.0099361204207576,
 0.0152903461870663,
 0.0158655254686974}

In [62]:
# pull row of expression matrix corresponding to gene
gene_row=ensg_expr_log2.loc[ensg_expr_log2['gene']==ensg]
gene_row

,gene,chr,start,end,TCGA-GM-A2DO,TCGA-OL-A6VQ,TCGA-E9-A295,TCGA-A2-A0YL,TCGA-AQ-A54O,TCGA-BH-A0E7,...,TCGA-D8-A27N,TCGA-A8-A08C,TCGA-E2-A150,TCGA-LL-A8F5,TCGA-AQ-A1H3,TCGA-A2-A1FW,TCGA-BH-A0E1.2,TCGA-BH-A0E1.3,TCGA-B6-A0X5,TCGA-S3-AA17
16109,ENSG00000205457,16,33206487,33207557,0.0,0.0,0.0,-3.153889,-2.847636,-22.827479,...,0.0,0.0,-5.355677,0.0,0.0,-4.447655,-4.470846,0.0,0.0,-6.401739

In [66]:
chrom=int(gene_row['chr'])

In [69]:
GENOS_DIR='~/Data/TCGA/imputed/split_chr'
traw_fh='white_imputed_rsID1.'+chrom+'.traw'

In [8]:
# check if plink2 --extract gets same TCGA patients as in *.ID file
pheno=pd.read_table('tmp/1_10/TCGA-BRCA_train.log2.txt.ENSG00000000419.pheno',header=None)
pheno.head()

                               0         1
0  TCGA-E9-A22D     TCGA-E9-A22D  5.861366
1  TCGA-LL-A73Y     TCGA-LL-A73Y  5.614071
2  TCGA-BH-A0HP     TCGA-BH-A0HP  5.148921
3  TCGA-AR-A24S     TCGA-AR-A24S  5.641648
4  TCGA-A2-A0CO     TCGA-A2-A0CO  4.911644

In [9]:
pheno_ids=[x.split()[0] for x in list(pheno.iloc[:,0])]

In [13]:
fam=pd.read_table('/cellar/users/jlz014/Data/TCGA/imputed/split_chr/white_imputed_rsID1.20.fam',sep=' ',header=None)

In [20]:
fam_ids=list(fam.iloc[:,0])

In [23]:
len(set(fam_ids)&set(pheno_ids))

367